services:
  db:
    image: postgres:15-alpine
    container_name: computer_store_db
    environment:
      POSTGRES_DB: computer_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  core-service:
    build: ./core-service
    container_name: computer_store_core
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/computer_store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

  report-service:
    build: ./report-service
    container_name: computer_store_report
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/computer_store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

  gateway:
    build: ./gateway
    container_name: computer_store_gateway
    depends_on:
      - core-service
      - report-service
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge