server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://core-service:8081
          predicates:
            - Path=/api/computers/**
        - id: report-service
          uri: http://report-service:8082
          predicates:
            - Path=/api/reports/**

        - id: core-health
          uri: http://core-service:8081
          predicates:
            - Path=/health/core
          filters:
            - RewritePath=/health/core, /actuator/health
        - id: report-health
          uri: http://report-service:8082
          predicates:
            - Path=/health/report
          filters:
            - RewritePath=/health/report, /actuator/health
        - id: gateway-health
          uri: http://localhost:8080
          predicates:
            - Path=/health/gateway
          filters:
            - RewritePath=/health/gateway, /actuator/health